// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../components/shared/interfaces/Media';
import { Author } from '../../../author/content-types/author/author';
import { Media_Plain } from '../../../../components/shared/interfaces/Media';
import { Author_Plain } from '../../../author/content-types/author/author';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Article {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description?: string;
    slug?: string;
    cover?: { data: Media };
    author?: { data: Author };
    blocks?: any;
  };
}
export interface Article_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  slug?: string;
  cover?: Media_Plain;
  author?: Author_Plain;
  blocks?: any;
}

export interface Article_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  slug?: string;
  cover?: number;
  author?: number;
  blocks?: any;
}

export interface Article_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  slug?: string;
  cover?: AdminPanelRelationPropertyModification<Media_Plain>;
  author?: AdminPanelRelationPropertyModification<Author_Plain>;
  blocks?: any;
}
