// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../components/shared/interfaces/Media';
import { Category } from '../../../category/content-types/category/category';
import { Media_Plain } from '../../../../components/shared/interfaces/Media';
import { Category_Plain } from '../../../category/content-types/category/category';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Origin {
  Marcala = 'Marcala',
  CopaN = 'Copán',
  Comayagua = 'Comayagua',}
export enum Roast {
  Claro = 'Claro',
  Mediano = 'Mediano',
  Oscuro = 'Oscuro',}

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    productName: string;
    slug?: string;
    description?: string;
    images?: { data: Media[] };
    active?: boolean;
    price?: number;
    origin?: Origin;
    roast?: Roast;
    isFeatured?: boolean;
    category?: { data: Category };
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  productName: string;
  slug?: string;
  description?: string;
  images?: Media_Plain[];
  active?: boolean;
  price?: number;
  origin?: Origin;
  roast?: Roast;
  isFeatured?: boolean;
  category?: Category_Plain;
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  productName: string;
  slug?: string;
  description?: string;
  images?: number[];
  active?: boolean;
  price?: number;
  origin?: Origin;
  roast?: Roast;
  isFeatured?: boolean;
  category?: number;
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  productName: string;
  slug?: string;
  description?: string;
  images?: AdminPanelRelationPropertyModification<Media_Plain>[];
  active?: boolean;
  price?: number;
  origin?: Origin;
  roast?: Roast;
  isFeatured?: boolean;
  category?: AdminPanelRelationPropertyModification<Category_Plain>;
}
